### ISSUE TITLE
`set` not appropriate for scopes?

### ISSUE THREAD

**Issue by rpwagner** [fair-research/native-login#21]
When loading tokens, the `requested_scopes` parameter is being converted to a set based on string input, which takes it down to individual characters. See line 22 in `storage_tools.py`. Not sure this is the intended behavior.

```
>>> from fair_research_login import NativeClient
>>> APP_NAME = 'Folder Sync Example App'
>>> CLIENT_ID = '079bdf4e-9666-4816-ac01-7eab9dc82b93'
>>> SCOPES = ('openid email profile '
...           'urn:globus:auth:scope:transfer.api.globus.org:all')
>>> tokens = None
>>> client = NativeClient(client_id=CLIENT_ID, app_name=APP_NAME)
>>> client.login()
{'auth.globus.org': {'scope': 'profile openid email', 'access_token': '<token>', 'refresh_token': '<token>', 'token_type': 'Bearer', 'expires_at_seconds': 1552005394, 'resource_server': 'auth.globus.org'}, 'transfer.api.globus.org': {'scope': 'urn:globus:auth:scope:transfer.api.globus.org:all', 'access_token': '<token>', 'refresh_token': '<token>', 'token_type': 'Bearer', 'expires_at_seconds': 1552005394, 'resource_server': 'transfer.api.globus.org'}}
>>> client.load_tokens(requested_scopes=SCOPES)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/fair_research_login/client.py", line 129, in load_tokens
    check_scopes(tokens, requested_scopes)
  File "/anaconda3/lib/python3.7/site-packages/fair_research_login/token_storage/storage_tools.py", line 22, in check_scopes
    set(requested_scopes)))
fair_research_login.exc.ScopesMismatch: Requested Scopes do not match loaded Scopes for Globus Auth. 
Current: {'openid', 'profile', 'email', 'urn:globus:auth:scope:transfer.api.globus.org:all'}
Requested: {'c', 'a', 'l', 'b', 'i', 'r', ':', ' ', 'p', 'g', 'f', 'n', 't', 'o', 'm', 'h', 'e', '.', 'u', 'd', 's'}
>>> set(SCOPES)
{'c', 'a', 'l', 'b', 'i', 'r', ':', ' ', 'p', 'g', 'f', 'n', 't', 'o', 'm', 'h', 'e', '.', 'u', 'd', 's'}
>>> 
```

**Comment by NickolausDS** [comment]
`oauth2_start_flow(requested_scopes=my_scopes)` seems to accept both a string separated by spaces and an itereable. We should probably check and support both types.

**Comment by NickolausDS** [comment]
Fixed
